### ISSUE TITLE
Please tell me: It crashes on my phone. The settings are according to the normal procedure. I am running Android 13. How can I run it stably in a higher version?

### ISSUE THREAD

**Issue by W1ndys** [Aurorum-Studio/flarum-app#12]
Please tell me: It crashes on my phone. The settings are according to the normal procedure. I am running Android 13. How can I run it stably in a higher version?

**Comment by Aurorum-Studio** [comment]
Sorry for replying so late. I just saw your issue. 

Emm, can you provide me with some details, like, what does it mean to "crash", does it mean that it's completely un-open-able, or does it mean that the website could not be fully load? BTW, if you're from China (I've browsed your profile, and seems you are), some mobile phone manufacturers in China disabled the webview function, it will be very helpful if you can provide your device's info.

p.s. I can speak and write Chinese, feel free to chat with me in Chinese if you want to.

**Comment by W1ndys** [comment]
谢谢你的回复，我目前不再参与 flarum 相关的工作了

再次感谢你的回复和开源存储库带来的帮助🎉🎉🎉

**Comment by Aurorum-Studio** [comment]
okok, 我前几个月都在忙学校的事情，没有看到你提交的issue，抱歉😂

我也很久没有参与Flarum相关开发了，Flarum是个好程序，但是还有很多需要填补的地方，我使用Flarum搭建的网站在年初全都遭遇黑客数据注入式攻击了😂

BTW，本项目不止可以用做Flarum的网站APP化，也可以用在基本所有架构的网站上，如果未来你在使用本项目时有任何疑问，欢迎提出🦊

**Comment by W1ndys** [comment]
非常感谢！

我这段时间也是在忙，哈哈哈h

对 flarum 需求不大了

或许可以用来绑自己的博客，不过暂时没这个需要

🎉🎉🎉
