### ISSUE TITLE
Can you help me generate a client?

### ISSUE THREAD

**Issue by huguadao** [Aurorum-Studio/flarum-app#8]
Hello, I downloaded your demo file and installed it. I think it's great.
The forum website I built with Flarum also wants to have such an Android client, but I'm not a programmer. Can you help me generate one? Thank you.

I didn't find your contact information. Please contact me by email:  huguadao#outlook.com

**Comment by Aurorum-Studio** [comment]
可以的捏，我注意到你应该是中国人，我就用中文了哈，emm, 就是我最近有些忙，可能也要过一两天才能给你，我需要你的域名和你想要的logo🦊.
Yes, I can generate one for you, but I'm a little busy these days, it might take a day or two to send you the final app. I need your domain name (URL), and logo to generate one. 
如果你有微信，可以微信联系我，我的微信号是：`XavierPatrick` . 申请备注：Github加你的称呼，如果没有，可以联系我的邮箱，`xavierpatrickwy@163.com`, 或者，`aurorum@aurorum.co` 。
If you have wechat, you can contact me searching my id `XavierPatrick`, and note as: Github+what you want me to call you., You can also contact me through email: `xavierpatrickwy@163.com`, or，`aurorum@aurorum.co` .

**Comment by Aurorum-Studio** [comment]
Issue Complete.
